groups:
  - name: soulsupport-alerts
    rules:

      # ---------------- FRONTEND ----------------
      - alert: FrontendDown
        expr: probe_success{instance="http://soulsupport-web:3000"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Frontend is down"
          description: "Frontend container is not responding on port 3000"

      # ---------------- BACKEND ----------------
      - alert: BackendDown
        expr: probe_success{instance="http://soulsupport-api:5007/health"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backend is down"
          description: "Backend health endpoint is not responding"

      # ---------------- MEMORY ----------------
      - alert: HighHostMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Host memory usage is above 85%"

      # ---------------- CPU ----------------
      - alert: HighContainerCPU
        expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High container CPU usage"
          description: "One or more containers are using high CPU"